export const USER_SIGNING_REQUEST = 'USER_SIGNING_REQUEST'
export const USER_SIGNING_SUCCESS = 'USER_SIGNING_SUCCESS'
export const USER_SIGNING_FAIL = 'USER_SIGNING_FAIL'


export const USER_SIGN_OUT = 'USER_SIGN_OUT'
